### ISSUE TITLE
Non-Localized texts in Workout Type selection

### ISSUE THREAD

**Issue by ffried** [HarshilShah/PeakLocalisations#5]
<img width="1389" alt="image" src="https://github.com/HarshilShah/PeakLocalisations/assets/1689782/7679918a-a750-4d95-9329-de29e1e1d43d">

**Comment by ffried** [comment]
A few more places. Possibly all fixed in one go:
<img width="1389" alt="image" src="https://github.com/HarshilShah/PeakLocalisations/assets/1689782/545930bd-4fb7-4e81-b1c7-6e25be511f58">
<img width="1389" alt="image" src="https://github.com/HarshilShah/PeakLocalisations/assets/1689782/cc656654-8431-436f-a704-d1b18113f9e4">
<img width="1389" alt="image" src="https://github.com/HarshilShah/PeakLocalisations/assets/1689782/dc6361af-526c-4b9d-b66d-ac5eb5d88f5e">

**Comment by HarshilShah** [comment]
Just pushed up a little commit that contains some new strings to fix this and the other issues, would be great if you could add the German translations and I can cut a build with those then!

**Comment by HarshilShah** [comment]
Here's the commit btw: 1c8b3459ae9bc2703a0100299853fe1856c13274
